[phases.setup]
nixPkgs = [
    "python38", 
    "python38Packages.pip",
    "poetry"
]

[phases.install]
cmds = [
    "poetry config virtualenvs.create false",
    "poetry install --no-interaction --no-ansi --no-root"
]

[start]
cmd = "python -m uvicorn main:app --host=0.0.0.0 --port=${PORT:-8000}"