# nixpacks.toml
[phases.setup]
nixPkgs = ["python38", "python38Packages.pip"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host=0.0.0.0 --port=${PORT:-8000}"

[watch]
paths = ["main.py", "requirements.txt"]